import 'package:equatable/equatable.dart';

/// Post-session care summary generated by the Summary Generator agent.
class CareSummaryModel extends Equatable {
  final String sessionId;
  final DateTime timestamp;
  final String injuryType;
  final String severity;
  final String patientDescription;
  final List<String> actionsTaken;
  final List<String> medicationsDiscussed;
  final List<String> followUpRecommendations;
  final List<String> warningSigns;
  final String disclaimer;

  const CareSummaryModel({
    required this.sessionId,
    required this.timestamp,
    required this.injuryType,
    required this.severity,
    required this.patientDescription,
    required this.actionsTaken,
    required this.medicationsDiscussed,
    required this.followUpRecommendations,
    required this.warningSigns,
    required this.disclaimer,
  });

  factory CareSummaryModel.fromJson(Map<String, dynamic> json) {
    return CareSummaryModel(
      sessionId: json['session_id'] as String? ?? '',
      timestamp: json['timestamp'] != null
          ? DateTime.parse(json['timestamp'] as String)
          : DateTime.now(),
      injuryType: json['injury_type'] as String? ?? '',
      severity: json['severity'] as String? ?? '',
      patientDescription: json['patient_description'] as String? ?? '',
      actionsTaken: List<String>.from(json['actions_taken'] as List? ?? []),
      medicationsDiscussed:
          List<String>.from(json['medications_discussed'] as List? ?? []),
      followUpRecommendations:
          List<String>.from(json['follow_up_recommendations'] as List? ?? []),
      warningSigns: List<String>.from(json['warning_signs'] as List? ?? []),
      disclaimer: json['disclaimer'] as String? ??
          'This was first aid guidance only. Dr. Muhammad is not a substitute for professional medical care.',
    );
  }

  CareSummaryModel copyWith({
    String? sessionId,
    DateTime? timestamp,
    String? injuryType,
    String? severity,
    String? patientDescription,
    List<String>? actionsTaken,
    List<String>? medicationsDiscussed,
    List<String>? followUpRecommendations,
    List<String>? warningSigns,
    String? disclaimer,
  }) =>
      CareSummaryModel(
        sessionId: sessionId ?? this.sessionId,
        timestamp: timestamp ?? this.timestamp,
        injuryType: injuryType ?? this.injuryType,
        severity: severity ?? this.severity,
        patientDescription: patientDescription ?? this.patientDescription,
        actionsTaken: actionsTaken ?? this.actionsTaken,
        medicationsDiscussed: medicationsDiscussed ?? this.medicationsDiscussed,
        followUpRecommendations:
            followUpRecommendations ?? this.followUpRecommendations,
        warningSigns: warningSigns ?? this.warningSigns,
        disclaimer: disclaimer ?? this.disclaimer,
      );

  Map<String, dynamic> toJson() => {
        'session_id': sessionId,
        'timestamp': timestamp.toIso8601String(),
        'injury_type': injuryType,
        'severity': severity,
        'patient_description': patientDescription,
        'actions_taken': actionsTaken,
        'medications_discussed': medicationsDiscussed,
        'follow_up_recommendations': followUpRecommendations,
        'warning_signs': warningSigns,
        'disclaimer': disclaimer,
      };

  @override
  List<Object?> get props => [
        sessionId,
        timestamp,
        injuryType,
        severity,
        patientDescription,
        actionsTaken,
        medicationsDiscussed,
        followUpRecommendations,
        warningSigns,
        disclaimer,
      ];
}
